### ISSUE TITLE
How install this code?

### ISSUE THREAD

**Issue by jatap** [madflow/flow-netbeans-markdown#1]
Hi madflow,

I'd like to install and test this code, is there any doc about it?

Thanks for your work.

**Comment by madflow** [comment]
Hi, the plugin is in early state. Right now - the only feature working is transforming a markdown source to HTML. I wasn't even able to create a nbm package that worked yet ;). 

If you really want to try it in this early stage - you can clone the repository and open/import the folder as a new Netbeans project. Afterwards you should be able to "run" this as a Netbeans module. For this you will need a fully bloated Netbeans Platform with Netbeans module development features.

Best regards
Florian

**Comment by jatap** [comment]
Ok, I thought it was a Markdown plugin to manage this type of files.

I've no time to help you developing this plugin now, it's a pity it looks useful.

## Greetings.

Julio Antúnez Tarín

Tel. móv.: (+34) 605 513 124
Skype: julio.antunez.tarin
E-mail: julio.antunez.tarin@gmail.com
