### ISSUE TITLE
CSS Option

### ISSUE THREAD

**Issue by junichi11** [madflow/flow-netbeans-markdown#10]
It is useful if user is able to set the css file to Option of Markdown plugin.
e.g. 
Plugin uses it when user run view action.
Actually, I tried to add css into source code. I think that it' good.

Currently, you are writing the all code into constructor of Markdown*Action currently.
Are there any reasons? (This is simply my question.)

Thanks.

**Comment by madflow** [comment]
I understand you refer to the HTML code wrapped around the actual editor content when serializing the Markdown string to HTML. The reason it is in the constructor is - that it is a complete **HACK** ;)

I was thinking about putting the mess in a sort of template which can be edited in the options menu. This would allow global CSS rules applied to every generate/view action.

For example:

![Options Menu](https://f.cloud.github.com/assets/183248/266813/3f379d7e-8e3c-11e2-8348-3cf8f644a8a0.png)

**Comment by junichi11** [comment]
If the code move to actionPerformed method, we happen to some problems, don't we? 

Oh, template option is very nice!!

Thanks a lot!

**Comment by madflow** [comment]
Is there any reason to move the code to actionPerformed?

**Comment by junichi11** [comment]
Please don't misunderstand me, it is no problem. You don't have to move it. It is a simple question for me. I asked you it since I thought that usually actual processing is wrote there (If there is nothing there, the action seems to do nothing. I thought that there might be some reason).

**Comment by madflow** [comment]
Okay - now I understand ;).  It is not "textbook java" to put logic in the constructor. But that is how it was proposed in a documentation I based this code on. I honestly do not know when in the application lifecycle "actionPerformed" is called. 

So my reason was: I did not now any better ;)

**Comment by junichi11** [comment]
I see. Thanks for your answer.
