### ISSUE TITLE
Integrate pegdown 1.6

### ISSUE THREAD

**Issue by madflow** [madflow/flow-netbeans-markdown#100]
Pegdown 1.6 hast been released - with a good amount of changes. 

https://github.com/sirthias/pegdown/releases/tag/1.6.0

This release will fix a lots of parser artifacts (i.e. #43) and introduce new features and plugins (i.e #54 ).

I would suggest to include these changes and prepare a new release afterwards!

**Comment by stengerh** [comment]
Just a heads-up: I've been working on this issue. It still needs some testing and the new syntax extensions from pegdown 1.6 have not been integrated yet. The current code is available on branch [issue-100-nb8](https://github.com/stengerh/flow-netbeans-markdown/tree/issue-100-nb8).

**Comment by spyhunter99** [comment]
any consideration for the atlassian markdown generator? i think it's called common mark

**Comment by stengerh** [comment]
I guess you mean https://github.com/atlassian/commonmark-java. I did a quick check and it does not provide token positions, so it is not usable for syntax highlighting.

**Comment by spyhunter99** [comment]
gotcha, just sharing info. thanks

**Comment by Chris2011** [comment]
I think you can close this ticket in case of deprecation of pegdown.
