### ISSUE TITLE
Can't strikethrough text

### ISSUE THREAD

**Issue by Chris2011** [madflow/flow-netbeans-markdown#102]
I saw here: https://de.serlo.org/hilfe-markdown that I can strikethrough text via ~~text~~, but the preview still shows me ~~text~~. In jira I know there is --text-- or only one I don't know. When I use the ~~ syntax in github, everything is fine.

**Comment by madflow** [comment]
Habe you activated the extension under "options"?

**Comment by Chris2011** [comment]
Thx, I didn't notice that. Its working. :)
