### ISSUE TITLE
Request validation for 8.1?

### ISSUE THREAD

**Issue by gonssal** [madflow/flow-netbeans-markdown#103]
I was using 8.0 and installed the plugin from the plugins portal.

After upgrading to 8.1, it doesn't seem to be there anymore. Could you request validation for inclusion in the portal for 8.1?

**Comment by vanquang9387** [comment]
+1

**Comment by madflow** [comment]
Hi, sure we should request a validation.  I just tried the latest release from https://github.com/madflow/flow-netbeans-markdown/releases . "Markdown Support 2.3 for NetBeans 8.0 ". This release installed fine and seems to work in 8.1. @stengerh  in #94 you already investigated in the api changes in 8.1. Do you believe we should try to compile the plugin under 8.1 or would the latest release suffice?

**Comment by gonssal** [comment]
That release doesn't work for me.

Tried installing and when I open a .md file the tab freezes and I get the following error:

`Error creating extended parser class: null`

NetBeans 8.1 on Ubuntu. I also tried the code from @stengerh repo and same error.

**Comment by stengerh** [comment]
It worked fine when I tried it on NetBeans 8.1 nightly. Something might have changed since then. I'll have to take a closer look.

**Comment by madflow** [comment]
Please see #105

**Comment by madflow** [comment]
Validation requested, lets see where it gets us :D
