### ISSUE TITLE
Use showURLExternal

### ISSUE THREAD

**Issue by junichi11** [madflow/flow-netbeans-markdown#11]
Hi,

https://github.com/madflow/flow-netbeans-markdown/commit/fd02649594d91e94190c10dfea847c0ff8937715
I think that plugin should use showURL because User can select the browser on `Tools > Option > General > Web Browser`.
What do you think about this?

Regards.

**Comment by madflow** [comment]
This commit was completely bogus. Thanks for the heads up!!!

**Comment by junichi11** [comment]
Thanks for fixing!
