### ISSUE TITLE
Horizontal rules don't work

### ISSUE THREAD

**Issue by nmatt** [madflow/flow-netbeans-markdown#110]
The preview and syntax highlighting doesn't seem to support horizontal rules.
Using version 2.3.1 under NetBeans 8.1.

**Comment by madflow** [comment]
Please post the text with the horizontal rule. Last time I checked - they worked :D 

Wild guess - maybe related to: https://github.com/sirthias/pegdown/issues/129

We are using an older version of pegdown without the `RELAXEDHRULES` option.

**Comment by nmatt** [comment]
Yes, that's it. I hadn't empty lines before/after the HR.
