### ISSUE TITLE
table syntax

### ISSUE THREAD

**Issue by lathspell** [madflow/flow-netbeans-markdown#115]
It would be nice if this table syntax would be added for the preview function:
* https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables 

It's not part of the "official" syntax but at least Github already understands it.

**Comment by madflow** [comment]
We use pegdown for parsing markdown and transforming to HTML.

https://github.com/sirthias/pegdown

It has a Table Plugin that can be enabled under ```Options->Miscellaneous->Markdown->Extensions```

Does this suffice?
