### ISSUE TITLE
Request : version number for plugin

### ISSUE THREAD

**Issue by junichi11** [madflow/flow-netbeans-markdown#12]
Hi, 

I think that you should update the plugin version when you create a new nbm.
Because... If user downloads new nbm(zip), user has to uninstall plugin and install new plugin again.

If version number for new nbm higher than installed nbm, user doesn't have to uninstall.
e.g.
new : 0.1.1 , old : 0.1.0 

Regards.

**Comment by madflow** [comment]
I definitely would version the plugin in the future - if there is any interest. I haven't considered it yet - because it is still in heavy development. Right now - this is just always the HEAD version.

The easy update remark is convincing though... So... 0.1.1 - 0.1.999 it will be ;)

**Comment by junichi11** [comment]
I know that you are developing this plugin yet. This is my request. 
If you don't want to do this, it is no problem (you don't have to do it) :)

> So... 0.1.1 - 0.1.999 it will be ;)

It's OK! It is useful for user :)

Thanks for your great works!

**Comment by angelxmoreno** [comment]
please document how we can help. this plugin would be very useful. very :-)

**Comment by madflow** [comment]
@angelxmoreno Thank you for your interest in the plugin. 

Of course specific bug reports, comments and suggestions help a lot! When it comes to bring the plugin to a state where I would consider it to be released on a plugin channel - the Lexer implementation has to be revamped.

> In case you do not know: The Lexer is the part where the editor content is translated into sequences of "Tokens" which can be given a certain attribute (like "bold" or "green text") for syntax highlighting. 

Right know - the implementation is flaky and only block elements like headings or lists are supported.

Fortunately - the great pegdown library (from @sirthias) already can translate a markdown file to a syntax tree of Tokens (Nodes). The next biggest step would be to completely facilitate this library for the Lexer. The implementation would have to be backed up by unit tests (I already started on this).

I can create some extra "issues" with the specific tasks for better documentation.
