### ISSUE TITLE
Recognize *.md.vm as markdown files

### ISSUE THREAD

**Issue by spyhunter99** [madflow/flow-netbeans-markdown#120]
Maven has this neat feature for generated sites. If the .vm extension is appended to the file, token replacement is then processed when the site is generated. Would it be possible to alter the plugin to also support that type of file extension?

**Comment by madflow** [comment]
I would argue that this should be user specific and created as a new file type association in NetBeans (Tools->Options->Miscellaneous->Files).  Create a new file type with `text/x-markdown` associated with it.

**Comment by spyhunter99** [comment]
oh neat, didn't even know that it existed. thanks!

**Comment by madflow** [comment]
👍

**Comment by spyhunter99** [comment]
@madflow so i did that, however netbeans won't let me enter `md.vm` as an extension. I think it must filter the dot. Adding just a `vm` as an extension with markdown mime type did not work immediately but after restarting nb, this plugin worked just fine. thanks again!

**Comment by thomas-mc-work** [comment]
I'd love to see that reopened. Netbeans doesn't allow to add filetypes with a `.` in the extension. The filetype `.md.vm` is being used by the maven site plugin. I think many people would benefit from that change. And I also think there won't be any side effects or regressions.
