### ISSUE TITLE
Please avoid warning about ineffective registration of resolver.

### ISSUE THREAD

**Issue by Chris2011** [madflow/flow-netbeans-markdown#122]
In general we don't look at warnings, but sometimes we should. When I start NetBeans and open the messages.log I see this warning:

```
WARNING [org.netbeans.modules.openide.filesystems.declmime.MIMEResolverImpl]: Ineffective registration of resolver Services/MIMEResolver/MarkdownResolver.xml use @MIMEResolver.Registration! See bug #191777.
```

In my opinion and it is written there, you should refactor the code to use the better implementation, because it seems not so ineffective.

Regards

Chris

**Comment by stengerh** [comment]
Hi, thanks for the suggestion. This was easy enough to refactor. I have to admit I could not reproduce this particular warning. Which versions of NetBeans and the Markdown plugin do you use?

**Comment by Chris2011** [comment]
Hey, thx for the fix. I use NetBeans 8.2 Patch 1 and Markdown Support is at 2.3.1.

**Comment by Chris2011** [comment]
Seems fixed. Thx.
