### ISSUE TITLE
Support for code block marker three back ticks (```) 

### ISSUE THREAD

**Issue by vdweij** [madflow/flow-netbeans-markdown#125]
Many implementations support a code block that is marked with three back ticks (```)  next to indenting text. The three backticks also allows for language highlighting.

Although it appears not be part of the initial [syntax](https://daringfireball.net/projects/markdown/syntax) it is supported by implementations used also by github. For example, this piece:

\`\`\`groovy
def myVar = 'foo'
\`\`\`

renders:

```groovy
def myVar = 'foo'
```
It would be awesome if the plugin also supports this markup

**Comment by madflow** [comment]
It is supported - but not the inline language highlighting like github does. You have to enable "Fenced Code Blocks" in the plugin options.

**Comment by vdweij** [comment]
awesome!!!
