### ISSUE TITLE
problems with numericals in links

### ISSUE THREAD

**Issue by thesebas** [madflow/flow-netbeans-markdown#2]
Plugin compiled on Netbeans 7.1

got this text:

```
this [TASK-123] is done and this [one] is not

  [TASK-123]: http://some.bugtracker:8443/browse/TASK-123 "task"
  [one]: http://some.bugtracker:8443/browse/TASK-125 "other"
```

converted to:
   `<p>this [TASK-{] is done and this <a href="http://some.bugtracker:84+/browse/TASK-}" title="other">one</a> is not</p>`

instead of:
   `<p>this <a href="http://some.bugtracker:8443/browse/TASK-123" title="task">TASK-123</a> is done and this <a href="http://some.bugtracker:8443/browse/TASK-125" title="other">one</a> is not</p>`

as on [dingus](http://daringfireball.net/projects/markdown/dingus)

note: _TASK-123_ changed to _TASK-{_ but also _some.bugtracker:8443_ to _some.bugtracker:84+_

**Comment by thesebas** [comment]
silly me: https://github.com/cletus/jmd/issues/1

**Comment by madflow** [comment]
I will probably switch to pegdown (https://github.com/sirthias/pegdown) since jmd does not seem to be supported ;)
