### ISSUE TITLE
Attach NBM to releases(tags)

### ISSUE THREAD

**Issue by junichi11** [madflow/flow-netbeans-markdown#25]
Could you attach a nbm to releases(tags) if possible? 
(not into project[nbm/flow-netbeans-markdown.nbm] but into releases)

It's possible with `Draft a new release`.

It will be convenient for NB user to attach one because some users are using specific NetBeans edition(e.g. PHP, C/C++).
They can't create a new nbm soon.

Thanks.

**Comment by madflow** [comment]
I created a draft now. (Cool - I did not know about this Github Hack yet).

**Comment by junichi11** [comment]
Perfect :+1: 

Thanks!
