### ISSUE TITLE
Project can't be opened in PHP only netbeans installation

### ISSUE THREAD

**Issue by jeroenvdgulik** [madflow/flow-netbeans-markdown#26]
I would like to use this plugin into my Netbeans with PHP only support, but the project is unrecognized. This is most likely because I don't have any of the Java plugins installed. Which plugin does Netbeans need to correctly open the project?

**Comment by madflow** [comment]
Hi,

the packaged plugin archives can be downloaded from Github:

[Releases Overview](https://github.com/madflow/flow-netbeans-markdown/releases) 

=> This is your best choice ! Install the plugin with: Tools -> Plugins -> Downloaded

Or...

 "NetBeans Plugin Development" plugin must be installed if you want to compile your own binary package.
1. git clone git://github.com/madflow/flow-netbeans-markdown.git
2. Open the folder with NetBeans (Open Project)
3. (Configure Target Platform if needed)
4. Choose "Create NBM" from the project menu
5. Install the plugin with: Tools -> Plugins -> Downloaded

**Comment by jeroenvdgulik** [comment]
Thanks for the quick reply!
