### ISSUE TITLE
Add Remove Trailing Whitespace exception on Netbeans

### ISSUE THREAD

**Issue by fredw** [madflow/flow-netbeans-markdown#27]
Hi, probably not the responsibility of you, but still like to check:
My Netbeans is configured to **Remove Trailing Whitespace**, so for all languages​​.
This is causing problems when you want to add line breaks in MD.
I wonder if there is a way to configure it not to do this with the MD files.
I tried adding the exception in `Options > Editor> Save On`, but the MD language does not appear in the list.

Thanks!

**Comment by junichi11** [comment]
@fredw 
I have created a patch for this issue.
If you can create a new nbm, checkout this branch and please try it.

@madflow 
Could you confirm it (and merge this changes if it's OK)?

Thanks.

**Comment by fredw** [comment]
Unfortunately, I can not create it.
I'll wait for the merge to be able to install the new version.

Thanks for agility.

**Comment by madflow** [comment]
I am AFK until Tuesday. If NetBeans supports this feature - we will merge/implement this for the plugin. :)

**Comment by stengerh** [comment]
I happily grabbed the source code a few day ago and added a few features which I missed. I should have checked the issue list before. My changes address this issue and at least one other. I guess I should learn how to use a pull request soon. ;)

**Comment by madflow** [comment]
@fredw I created a pre-release (1.3.1) with the patch from @junichi11 .

https://github.com/madflow/flow-netbeans-markdown/releases

I do not use this feature - and I honestly do not known exactly what the expected behavior is. I would be great if you could install and test the 1.3.1 package.

**Comment by madflow** [comment]
@stengerh Great! Please be so kind an create a pull request if you like. The basic process is that you create a separate branch for your patches (like "my-super-plugin-patch") and push this branch to your remote fork on Github. Than you select this branch on Github and create a pull request via the web interface. Github will do the rest ;)

**Comment by fredw** [comment]
Perfect! This worked.
Thanks to all.
