### ISSUE TITLE
Re-integration of fork

### ISSUE THREAD

**Issue by stengerh** [madflow/flow-netbeans-markdown#29]
I have recently forked your plugin to add a few little things. This turned into a coding spree which almost doubled the size of the source code. So unfortunately, I do not have small, self-contained patches for individual features. I also do not want to split the user base of this plugin or interfere with your plans for the plugin so I would prefer if my changes were re-integrated into your version.

As I am not very familiar yet with GitHub (and Git) I do not know which would be the best way to do this. I encourage you to look at my version and pick the features you like. :) I have also uploaded a pre-release so everyone can take a look without having to compile the plugin first.

Please tell me if you want me to extract a particular (set of) features as a patch!

Major changes:
- Preview tab in the editor showing a live preview, i.e. it uses the current content of the document in the editor, not the content of the file on disk.
- Support for the Navigator window
- Partial support for bread crumbs
- Code folding
- Configurable fonts and colors for syntax highlighting

**Comment by madflow** [comment]
Hi,

> I really like the term "coding spree" :)

I consider this plugin to be in an ongoing development stage - so I applaude new features as far as they do not introduce a reggression how existing features work (and should).

I quickly reviewed your changes and as far as I can tell they do fit nicely in the existing functionality. The navigator window was a pending feature request - and there also was a request for custom colors. The bread crumbs are nice to have.

The preview pane is a nice addition - it might be a little bit confusing with regards to the existing preview functionality - but this can  be explained in the docs.

I managed to allow some styling of the preview when adding:

```
previewTextPane.getDocument().putProperty("IgnoreCharsetDirective", Boolean.TRUE);
```

and changing:

```
//final String previewText = "<html>\n<head>\n</head>\n<body>\n" + bodyText + "</body>\n</html>";
final String previewText = MarkdownGlobalOptions.getInstance().getHtmlTemplate().replace("{%CONTENT%}", bodyText);
return previewText;
```

in the `MarkdownPreviewMVElement` class.

Maybe this will work...

I will check how easily this can be merged. Future merges should be best made via a pull request.

Thanks!!!

**Comment by stengerh** [comment]
The preview pane was actually the very reason I started working on the code. I wanted something like the existing preview function but inside the editor and based on the current editor contents. I deliberately left out customization in for now given Swing's limited HTML and CSS support.

To be honest I had not realized the plugin would open the preview HTML in the IDE _if the user has enabled the embedded browser_. Which I normally have not. ;) I wondered who would use preview-on-save since it would always switch to another application.

I still think it would be good to unify the two preview approaches in the long run. I'll let you know if I have an idea.
