### ISSUE TITLE
Colors of MD

### ISSUE THREAD

**Issue by elimc** [madflow/flow-netbeans-markdown#3]
Hey, thank you so much for MD support. I do have a question about colors of the .md files. My colors in the .md file look ugly, and I have no idea where to change the blue color in the .md file. I have gone through the fonts and colors editor and I don't see anything blue. Check out the image to see what I mean:
![mdColors](https://f.cloud.github.com/assets/1510615/204065/8f732b76-815f-11e2-829a-72bf936ec76d.PNG)

Is the blue color set inside the NBM?

**Comment by madflow** [comment]
Hi,

thank you for the feedback. Yes - the colors a set by the plugin. Unfortunately - the syntax coloring is _sort of_ unfinished. Nevertheless I took a shot at the issue by simple defining the Netbeans standards "keyword" for Headings and Lists, and "comment" for blockquotes. I tested this with my Linux box and different themes - now the plugin behaves similar to i.e. the colors in the XML Editor.

Of course I would appreciate a test on your side.

Thanks Florian

**Comment by elimc** [comment]
Thanks for the quick response. Just did a test and everything is looking much better:
![mdColors](https://f.cloud.github.com/assets/1510615/207316/0f2feba6-81ec-11e2-8776-4abf79a42282.PNG)

It would be nice if NetBeans could officially support .md files. As you can see in the screenshot, I would love to be able to add color hinting for things like URLs and lists. That might exceed the boundaries of your plugin. BTW, you can check out the theme I have created for NetBeans, here: https://github.com/elimc/ZenburnX. It is designed to be easy on the eyes.

**Comment by madflow** [comment]
Yes - It would be great if this filetype would find it's way to the core modules. Internally all Netbeans features are plugins (modules), too. The boundaries are just my limited resources ;) The problem with Markdown is - that there are many variations and flavors out there. I reckon these non-standards could prevent a core implementation.

I already implemented basic list support - but I did not include the "*" syntax.

**Comment by elimc** [comment]
Hey, I appreciate the plugin and support. I'm guessing you have seen this, but it looks like there may be hope for some sort of MD standardization to take place: http://www.codinghorror.com/blog/2012/10/the-future-of-markdown.html

Consider this issue closed.
