### ISSUE TITLE
List Elements in new Lexer

### ISSUE THREAD

**Issue by madflow** [madflow/flow-netbeans-markdown#34]
I tested the latest Lexer implementation and no List Elements seemed to be tokenized at the moment.

```
+ Hello
- Hello
* Hello
```

All throw an `java.lang.IllegalStateException: No token on stack`.

```
Product Version: NetBeans IDE 7.4 (Build 201310111528)
Java: 1.7.0_17; Java HotSpot(TM) 64-Bit Server VM 23.7-b01
Runtime: Java(TM) SE Runtime Environment 1.7.0_17-b02
System: Linux version 3.10-2-amd64 running on amd64; UTF-8; de_DE (nb)
```

**Comment by madflow** [comment]
This also applies to ordered lists:

```
1.  Bird
2.  McHale
3.  Parish
```

**Comment by stengerh** [comment]
I found the culprit. The fix is easy but I will add some more unit tests before I submit a pull request.

**Comment by madflow** [comment]
Works now. Thanks! I really like the new implementation.
