### ISSUE TITLE
Better HTML rendering for preview pane

### ISSUE THREAD

**Issue by stengerh** [madflow/flow-netbeans-markdown#36]
I looked for ways to improve the preview pane since Swing's HTML capabilities are quite limited. In particular I searched for ways to use the WebView from JavaFX 2. Given that recent NetBeans versions already uses this for the embedded web browser it seemed liked the best option. However I encountered some problems so I created this issue to document them.
1. The [HtmlBrowser](http://bits.netbeans.org/7.4/javadoc/org-openide-awt/org/openide/awt/HtmlBrowser.html) class can be used to embed a browser into any Swing component. However I had to select the right [factory](http://bits.netbeans.org/7.4/javadoc/org-openide-awt/org/openide/awt/HtmlBrowser.Factory.html) myself by enumerating the available factories and checking the class name (ugh). Otherwise the HtmlBrowser would end up picking the swing based browser factory.
   
   Even then what you get is an embedded browser, not just an HTML renderer. This means if the user clicks on a link the browser will navigate to that link. There are no hooks to prevent this or open the clicked link in an external browser. We could try to use a PropertyChangeListener to revert the URL change (there is no VetoableChangeListener) or inject some JavaScript into the HTML document to disable navigation but I don't like either approach.
2. The [WebView](http://docs.oracle.com/javafx/2/api/javafx/scene/web/WebView.html) can be used directly (via a JFXPanel) but this requires to get the JavaFX 2 runtime on the class path.
   1. Several tutorials for using JavaFX 2 in a NetBeans module suggest to embed the jfxrt.jar into a module. Licensing issues aside this would add almost 13 MB (for Javafx 2.2) to the NBM.
   2. NetBeans IDE seems to take a different approach for the embedded WebView based browser. However I don't know yet how they do it.
   3. Another option would be to wait for Java 8 when the JavaFX classes will be on the class path by default.

Comments are welcome.

**Comment by stengerh** [comment]
I have found a way to access the JavaFX runtime dynamically, i.e. by checking for the availability of JavaFX at runtime and then load my UI classes using reflection and a manually constructed class loader. The answer to ["I need to add a library JAR from outside the NetBeans installation"](http://bits.netbeans.org/dev/javadoc/org-openide-modules/org/openide/modules/doc-files/classpath.html#q-and-a) in the desciption of the class loader hierarchies in the NetBeans platform was very useful. I am going to clean up my code a bit before creating a pull request.

**Comment by stengerh** [comment]
It turns out that this approach leads to a conflict with other plugins using JavaFX, notable the Embedded WebKit Browser of the IDE. The cause is that each such plugin loads the JavaFX runtime using a separate class loader. Since JavaFX requires native libraries and a native library can only be loaded by a single class loader an error occurs when a second plugin tries to load JavaFX classes. The result is usually a locked up IDE.

Perhaps we should delay the introduction of this feature into the trunk until NetBeans 8. NetBeans 8 introduces an official wrapper module for the JavaFX runtime which will eliminate such classes loader problems.

I have uploaded a [pre-release](https://github.com/stengerh/flow-netbeans-markdown/releases/tag/v1.5.1-experimental) should anyone want to try the feature.

See also
- http://wiki.netbeans.org/DevFaqClassLoaders
- http://wiki.netbeans.org/DevFaq2SrcPaths

**Comment by madflow** [comment]
Thank you for your investigation. I would vote for delaying this feauture in favor of a more stable approach in NetBeans 8.

Thanks again!
