### ISSUE TITLE
Preview jumps to bottom on load

### ISSUE THREAD

**Issue by lakhman** [madflow/flow-netbeans-markdown#42]
I am using Netbeans 7.4 with this flow markdown plugin. It works great aside from the fact that when I click "preview" (after entering some markdown text), the preview scrolls (jumps) to the bottom.

The markdown text I am using to test is here: 
http://daringfireball.net/projects/markdown/syntax.text

Great plugin! thanks so much!, you should make it available through netbeans plugin updater!

**Comment by madflow** [comment]
Hi,

thank you for your interest in this plugin. It is a community effort!

I can confirm this behavior (Linux, Netbeans 7.4) and I agree it should be changed.

**Comment by lakhman** [comment]
Great!

I found this bug when using netbeans "Clone" window feature, basically I wanted to have 2 windows of my file open, The first would be the file itself (ie all markdown code), and the second window (which is the clone), would be the preview, so whenever I save my document, I want the "Preview" (cloned) window to be updated.

So kind of like a "live" preview (on each save of course) feature, I suspect this will work as soon as the above bug (snap to bottom) has been fixed! (and would be such a great little feature!!)

I'd love to get my head into a netbeans plugin, perhaps I'll fork and learn whilst I play!

Thanks for everyone would contributed to this plugin, it's so useful!

**Comment by stengerh** [comment]
I noted this behavior early during the development of the preview function. I know it can be changed to jump to the top instead ;)

So far I have not investigated this further as the changes will probably not apply to the fancy JavaFX based preview we will hopefully soon have (at least on NetBeans 8).

**Comment by madflow** [comment]
~~@stengerh I fixed (at least tried to, feel free to evaluate the commit) this in master - since I believe there will be a "nb7" branch for a while.~~ (Fix did not work. Commited prematurealy)

Thanks for reporting this!

**Comment by madflow** [comment]
2nd Try. Now it is just nailed to top the top (better than to the bottom I guess).

**Comment by DarrenCook** [comment]
I just installed the markdown plugin and have the same problem: after any edit the preview window jumps to the bottom. Ideally its top line would match the top line in the editor, but simply not scrolling anywhere would be a good enough second choice!
I'm using netbeans 8.0.2, and got the plugin through the UI, i.e. latest version from plugsin.netbeans.org.

**Comment by stengerh** [comment]
I prepared a [pre-release](https://github.com/madflow/flow-netbeans-markdown/releases/tag/2.3-preview) containing the recent changes to preserve the scroll position. You are invited to test this pre-release if you do not want to compile the plugin from source code.

**Comment by Chris2011** [comment]
I found a desktop app in chrome store called minimalist markdown editor. You can scroll in the editor view and the preview view scroll too. So if you split the document and see the preview it should be good that you can scroll both at the same time or you create a split view by your own, maybe this plugin can help you to create your own split view with simultanous scrolling: https://github.com/markiewb/nb-codeoutline
