### ISSUE TITLE
Lexer artifact with lists 

### ISSUE THREAD

**Issue by madflow** [madflow/flow-netbeans-markdown#43]
When I write some lists elements like this with latest code base:

```
+ List 1

+ List 2
+ List 3
```

It results in this:

![bildschirmfoto vom 2014-01-28 15 52 06](https://f.cloud.github.com/assets/183248/2019995/57569a32-882c-11e3-8a76-cf0e2a8f9842.png)

I have not debugged this further and this is actually not a sane way to write this  - but now we have it documented ;)

**Comment by stengerh** [comment]
Interesting, I'll have to check the PegDown AST for this input. :)

**Comment by stengerh** [comment]
I experimented a bit and noticed this behavior under the following conditions:
- This happens with any kind of list.
- The list has to be the first one in the document.
- There has to be an empty line after the first list item.

**Comment by madflow** [comment]
I believe the list must not necessarily be the first in the document. For example:

```
# Hello

+ L1
+ L2

+ L3

+ L4

# Hello 2

+ L5
+ L6

+ L7
+ L8
```

Always the last `+` is not highlighted correctly.

**Comment by stengerh** [comment]
Okay, I thought you were talking about the highlighted text of the first list item. So there are two oddities here. I changed the background of list items (yellow), bullet lists (orange) and ordered lists (green) to make it more obvious:
![image](https://f.cloud.github.com/assets/3945287/2061193/40826ef8-8c46-11e3-95fd-6abc8041aae6.png)

**Comment by madflow** [comment]
Yes - sorry. In the first case it was the first Item. Two issues here...

**Comment by madflow** [comment]
Closing - since a pegdown version bump would fix this :o
