### ISSUE TITLE
 Collaborators accounts

### ISSUE THREAD

**Issue by madflow** [madflow/flow-netbeans-markdown#45]
Hi,

@stengerh , @junichi11 

I added your accounts as "Collaborators" for this repository. I do not know what you can do or not do though.

The github help says you have read-write permissions  - so I assume you can now push to the repo directly. Maybe other things work now aswell? (Like creating Issue labels or merge pull requests via the web form).

I would suggest to keep up the clone/patch/create pull request/merge procedure on almost all changes - so we can have a quick review.

When it comes to fixing smaller bugs, Readme changes or other smaller tasks - I would encourage you to merge into master (or upcoming other branches respectively) as you like.

If you do not want to be listed as collaborator: please let me know!

**Comment by junichi11** [comment]
@madflow 
Thanks a lot !

**Comment by stengerh** [comment]
Thanks from me as well! The suggested workflow sounds good to me.
