### ISSUE TITLE
Feature Request: Add custom css to the "preview" pane

### ISSUE THREAD

**Issue by lakhman** [madflow/flow-netbeans-markdown#46]
Hi,

I have a small feature request, I would like to be able to style the CSS in the "preview" pane. So perhaps I could go into the settings and add some custom css that would be applied to the preview pane (So this would be application wide).

I use markdown to document things throughout my application, and being able to style it to be more easily readable would be so useful!

**Comment by madflow** [comment]
Hi,

thanks for the feature requests. This is already documented here #31 and here #36 - so I am closing this issue as a duplicate. When #36 is resolved or we can make #44 work - then we can tackle this feature.
