### ISSUE TITLE
Modify background color on Preview

### ISSUE THREAD

**Issue by jonathanvila** [madflow/flow-netbeans-markdown#48]
Hello.

I'm using Netbeans 8 with the dark look and feel and the Preview tab uses a dark background color and the font color is black so I can see almost nothing.

Is there a way to change the background color for the preview ?

**Comment by stengerh** [comment]
No, we don't have a setting for this.

Do you use the stable version of the plugin or the experimental version with the JavaFX-based preview renderer? In the latter case you could work around this issue by setting the text and background colors via CSS in the HTML template. Although this would also affect the exported HTML.

The Swing based renderer seems to mix settings from the built-in stylesheet and from the platform UI defaults. I'll look at how we can make it use a consistent color scheme (i.e. one which results in readable display).

**Comment by madflow** [comment]
Please try the latest release for NetBeans 8.0 if possible. Thanks
