### ISSUE TITLE
Miscellaneous option "Save in same folder" does not save

### ISSUE THREAD

**Issue by lakhman** [madflow/flow-netbeans-markdown#50]
I am using netbeans version 7.4 (spec below), When I check the option in the settings (Options > Miscellaneous > Markdown > Miscellaneous > "Save in same folder as markdown file"), It works for that session, but when I restart netbeans, the option reverts back to "unchecked", The "View HTML on save" option works fine and persists between sessions, but the "save in same folder" only works for that session, and then reverts to unchecked when netbeans is restarted.

Is this just an issue with my version of netbeans or is this a genuine bug? (Can it be reproduced by others)

```
// Spec from `About Netbeans`
Product Version: NetBeans IDE 7.4 (Build 201310111528)
Updates: NetBeans IDE is updated to version NetBeans 7.4 Patch 2
Java: 1.7.0_51; Java HotSpot(TM) 64-Bit Server VM 24.51-b03
Runtime: Java(TM) SE Runtime Environment 1.7.0_51-b13
System: Mac OS X version 10.9.1 running on x86_64; UTF-8; en_US (nb)
```

**Comment by stengerh** [comment]
This is a bug. The `load` method in class [MarkdownPanel](https://github.com/madflow/flow-netbeans-markdown/blob/master/src/flow/netbeans/markdown/options/MarkdownPanel.java) does not update the state of the checkbox according to the configured value.

**Comment by madflow** [comment]
Hi, 

thanks for reporting! This feature used to work - but was br0ken "along the way".

We killed it here: https://github.com/madflow/flow-netbeans-markdown/pull/39 I think ;)

I fixed it in master.
