### ISSUE TITLE
There is not syntax highlighting for PHP

### ISSUE THREAD

**Issue by avz-cmf** [madflow/flow-netbeans-markdown#60]
I write:

```PHP
     /**
      \* @param array
      \* @return void
      */  
     public function setService($servicesConfig)
     {
         $this->_servicesConfig = $servicesConfig;
     }
```

I get:

PHP /*\* \* @param array \* @return void */ public function setService($servicesConfig) { $this->_servicesConfig = $servicesConfig; }

**Comment by stengerh** [comment]
Did you enable the fenced code blocks extension in the plugin's options?

**Comment by avz-cmf** [comment]
I did not. Tell me pls how I can do it or where I can read about it.

**Comment by madflow** [comment]
Please consult the Readme.md file in this repository for  the fenced code blocks extension in the plugin's options.

Please note that this will not actually "highlight" the code. It just wraps it in "code" tags.
