### ISSUE TITLE
Split view for source and preview

### ISSUE THREAD

**Issue by Chris2011** [madflow/flow-netbeans-markdown#61]
I really like the feature to see the preview, but I don't want to jump to the preview and loose the focus for my source. And what happens if I check the checkbox "View Html on save" is that each time I save, it opens a new tab. What I prefer is a sync function with the opened tab.
My workaround to see the preview inside netbeans is to duplicate the file inside netbeans (only possible with the mouse) and set the view to preview of the duplicated file. This is ok but most of the time I use shortcuts for such things. So what I prefer is a shortcut to split your view (horicontal/vertical) to see the source and the preview inside netbeans.

Regards

Chris

**Comment by stengerh** [comment]
My initial impression is that a keyboard shortcut to split the view is a generic feature which would belong in the window manager module. I don't know yet if there is a suitable API to implement such a function in the markdown plugin.

**Comment by Chris2011** [comment]
Ok I think you are right and I see it too, I will file a bug for netbeans. Thx.
