### ISSUE TITLE
Please add code completion while typing.

### ISSUE THREAD

**Issue by Chris2011** [madflow/flow-netbeans-markdown#62]
The Code completion only works, after typing a t and than hit Ctrl + Space. It would be better to have code completion on type. Maybe this could be handled via option.

Regards

Chris

**Comment by madflow** [comment]
Hi there,

this is integrated in a "standard" feature of NetBeans called CodeTemplates. There you can only configure how to expand the code template. Trying to override this behavior is beyond the scope of this plugin.

**Comment by Chris2011** [comment]
But if it is a standad feauter, and yeah I know it, the code completion doesn't appears after typing a character or a word. It only appears after typing the character and hit Ctrl + space.

**Comment by madflow** [comment]
It is not code completion! It is the code template feature.

That's how the feature works, isn't it? When I create a Javascript File and I want to use the code templates - it is the same behavior. Type a + CTR-SPACE you'll get `alert()` and so on.

**Comment by Chris2011** [comment]
Ahh ok I see, sry for that, didn't know it. For some code templates I know the shortcuts so if or ife or so, so for these I didn't need the hint. Thx
