### ISSUE TITLE
Better support for pre-formatted data in the preview; hard to use

### ISSUE THREAD

**Issue by wadechandler** [madflow/flow-netbeans-markdown#66]
In my README.md file, I have this:

``````
"```
deployer.username
deployer.password
deployer.release.url
deployer.snapshot.url
download.url
```"
``````

and in preview it looks like a single line such as:
`deployer.username deployer.password deployer.release.url deployer.snapshot.url download.url`

I also have odd results with Java files and "```". I even see the tick marks in the preview.

I think this would be a higher priority for use than code completion in other issues I saw.

**Comment by wadechandler** [comment]
I'm attaching a screen shot of what this looks like on my Mac running under Java 1.7 in NetBeans 8.0.1.

Here is a shot of the source in the editor:
![md-plugin-source](https://cloud.githubusercontent.com/assets/779194/5683495/5f8f100a-97f6-11e4-8b64-e5c45cc095ba.png)

Then one of what preview shows:
![md-plugin-preview](https://cloud.githubusercontent.com/assets/779194/5683502/73723afc-97f6-11e4-858c-f7ec5b8bc588.png)

Thanks

**Comment by madflow** [comment]
Hi there!

Please enable "FENCED CODE BLOCKS" under Options->Miscellaneous->Markdown->Extensions

This should do the trick.

**Comment by wadechandler** [comment]
Very very nice! I already loved your plugin (just found it today ... see my comments on the NB plugin portal ...) ... Now I love it more! Perfect. Thanks so much. I will close this issue.
