### ISSUE TITLE
"<unrecognized project; missing plug-in?>"

### ISSUE THREAD

**Issue by devdrops** [madflow/flow-netbeans-markdown#67]
I can't install this plugin on my local environment.

**Specs:**
- NetBeans 8.0.2 (PHP Development dist)
- Macbook Pro with OSX Yosemite 10.10

When I follow the 'Installation' steps, on the 2nd step 'Open the folder with NetBeans (Open Project)', NetBeans display `<unrecognized project; missing plug-in?>` and I can't proceed with the instalation.

**Comment by madflow** [comment]
Hi,

If you want to compile your own package you will have to meet the requirements first:

> "NetBeans Plugin Development" plugin must be installed if you want to compile your own binary package.

If you just want Markdown-Support - you can download a pre-packaged release:

https://github.com/madflow/flow-netbeans-markdown/releases

https://github.com/madflow/flow-netbeans-markdown/releases/download/2.0/flow-netbeans-markdown.nbm

> Install the plugin with: Tools -> Plugins -> Downloaded

**Comment by devdrops** [comment]
@madflow thank you! I've downloaded the .nbm package and now everything works just fine! :+1:
