### ISSUE TITLE
Preview contains only a few 

### ISSUE THREAD

**Issue by jerry1970** [madflow/flow-netbeans-markdown#73]
I installed the plugin in NB 8.0.2 on Win8. Some syntax highlighting works and some is parsed correctly into the preview but some other things are not.

For example:

``````
# Header
This is some text

## Second header
Here is a link to http://www.github.com and an email address in someone@gmail.com .

~~~strike through~~~

Some table:

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

    ``` css
    .blah {
        color: black;
    }
    ```
``````

is parsed like the attachment.

I assume this has to do with the MD parser. I guess I have a very limited parser on my system. How do I set a reference to a different parser or install a new one?

Thanks!

![md](https://cloud.githubusercontent.com/assets/5627407/6635395/eedf7fb0-c965-11e4-8c76-d7d3688c96e2.png)

**Comment by madflow** [comment]
Please visit:

Options->Miscellaneous->Markdown->Extensions

and enable the missing extensions and try again ;)

**Comment by madflow** [comment]
Strike-Through will only work with the latest development branch though. Compiling your own package from source is pretty easy though.

We use pegdown (https://github.com/sirthias/pegdown) for parsing, syntax highlighting and HTML serialization. You cannot choose another one.

**Comment by jerry1970** [comment]
Ahhhh, thanks! I opened the Options dialog and searched for `markdown` but that didn't give any results so I (incorrectly) assumed there were no plugin options. Silly, I should have checked the Misc tab of course.

Works like a charm now, thanks!

No need to select another markdown parser now.
