### ISSUE TITLE
Markdown not appearing in new file wizard

### ISSUE THREAD

**Issue by thomasalbertlane** [madflow/flow-netbeans-markdown#75]
I have installed the flow-netbeans-markdown.nbm version 2.1 plugin in Netbeans IDE 8.0.2.
I am running OS X Yosemite 10.10.2 on a Macbook pro.
After restarting Netbeans, Markdown does not appear in the new file wizard.
I presume it should appear in the "Other" category along with "HTML File" etc?
Markdown options do appear in the "Preferences/Miscellaneous" section.
Tom.

**Comment by rmburkhead** [comment]
I am running the same version of both the plugin and the IDE on Win 8.1 and "Markdown file" correctly appears as the first item under "File Types" when "Other" is selected.

**Comment by thomasalbertlane** [comment]
Thanks for the information rmburkhead, it therefore appears to be a conflict/problem when running on OS X.

**Comment by madflow** [comment]
Weird... Same IDE Version on a Linux machine with java version "1.8.0_25" - I also see "Markdown file" under "Other". Sort of hard to debug...

**Comment by srsbiz** [comment]
Checked on OS X 10.10.2 with jre 1.8.0_40 NB 8.0.2 and plugin v 2.1 & 2.0 - for both there is "Markdown file" in "Other" category

**Comment by thomasalbertlane** [comment]
My apologies everyone, I just created a project, and now when I create a new file I find Markdown (as well as a lot of others that were not there before).
Thanks very much for your help, it kept me searching to find the problem.

**Comment by stengerh** [comment]
I could reproduce the issue. The Markdown template only shows up if there is at least one open project. Perhaps there is a different way to register our template which would make it always available.

**Comment by thomasalbertlane** [comment]
That could be useful, I used Netbeans a lot a couple of years ago when I was developing a Ruby on Rails website and I never created a Netbeans project.

**Comment by markiewb** [comment]
See
http://bits.netbeans.org/8.0/javadoc/org-openide-loaders/apichanges.html#TemplateRegistration.requireProject

Best regards, markiewb
