### ISSUE TITLE
List with multiple paragraphs handling

### ISSUE THREAD

**Issue by TiS** [madflow/flow-netbeans-markdown#76]
I have following markdown:

```
2. XYZ
    1. A

        - XYZ
        - XYZ
        - XYZ

        Lorem ipsum...

    2. B
        - XYZ
        - XYZ
        - XYZ
```

As you see, GitHUB (and other MarkDown editors I checked) render this as follows:
1. XYZ
   1. A
      - XYZ
      - XYZ
      - XYZ
      
      Lorem ipsum...
   2. B
      - XYZ
      - XYZ
      - XYZ

Unfortunately, this plugin treats first sub-sub list (and the Lorem Ipsum) as code block. What's more, it restarts list numbering for sub-list (A,B).

Happens on 2.1 release. Haven't tested master branch.

**Comment by madflow** [comment]
Hi there, we use https://github.com/sirthias/pegdown for parsing a markdown document, syntax highlighting and HTML Preview.  It is Java's Best for this task.

This looks like a bug in this library. Maybe you could create a bug ticket over there? We usually do not add our own markdown flavour to the library - but rely on its progress.

**Comment by TiS** [comment]
There was a similar issue there (https://github.com/sirthias/pegdown/issues/123). I've added my example in comment.

**Comment by madflow** [comment]
:+1:
