### ISSUE TITLE
Update file icon

### ISSUE THREAD

**Issue by rmburkhead** [madflow/flow-netbeans-markdown#78]
Dustin Curtis (Github: @dcurtis) has created a Markdown mark suitable for use as a markdown file icon. Github appears to have adopted it (look closely at the top of any Github edtiable text box where it says "Markdown supported"). There appears to be no licensing issues, as Dustin has released it to the public domain (CC0 license). Finding an appropriate place to provide attribution would be good though.

Make use of the mark as a file icon.

**Comment by rmburkhead** [comment]
There are two versions of the mark. One that has a transparent background, the other that is solid black. The solid black version would not work well with darker IDE themes. Working on a pull req using the one with a transparent bkgnd, but filling it to white.

**Comment by stengerh** [comment]
The attribution could go into the plugin description. The description is displayed in the NB plugin manager.

**Comment by rmburkhead** [comment]
To my eye, the file icon with a white background and no 1px border seems to be the best fit for either theme.

Thoughts? (clicking on the images will give you a slightly bigger version)

## Default light theme

| BG Color | No 1px border | w/1px border |
| --- | --- | --- |
| White | ![md-icon-wht-noborder-lttheme](https://cloud.githubusercontent.com/assets/255075/6737803/3188d734-ce2b-11e4-9125-c22b9b494dae.jpg) | ![md-icon-wht-border-lttheme](https://cloud.githubusercontent.com/assets/255075/6737800/3186bab2-ce2b-11e4-8867-99d9277f3fd4.jpg) |
| Black | ![md-icon-blk-noborder-lttheme](https://cloud.githubusercontent.com/assets/255075/6737802/318757b0-ce2b-11e4-8c3e-68d03f906bac.jpg) | ![md-icon-blk-border-lttheme](https://cloud.githubusercontent.com/assets/255075/6737798/317a8224-ce2b-11e4-9d7d-dc4309512657.jpg) |

## Dark L&F theme

| BG Color | No 1px border | w/1px border |
| --- | --- | --- |
| White | ![md-icon-wht-noborder-dktheme](https://cloud.githubusercontent.com/assets/255075/6737804/3189ddaa-ce2b-11e4-9ed7-f455475107e0.jpg) | ![md-icon-wht-border-dktheme](https://cloud.githubusercontent.com/assets/255075/6737799/3186c6ce-ce2b-11e4-89b4-3c611404ba5f.jpg) |
| Black | ![md-icon-blk-noborder-dktheme](https://cloud.githubusercontent.com/assets/255075/6737801/31872484-ce2b-11e4-9ae0-20de3592b0de.jpg) | ![md-icon-blk-border-dktheme](https://cloud.githubusercontent.com/assets/255075/6737797/316bccde-ce2b-11e4-9cea-fb15aac39ee0.jpg) |

**Comment by rmburkhead** [comment]
@stengerh I did a quick review of other plugins, and none seemed to provide any attribution in the descriptions they provide. I opted to add it to the Resources section of the Readme.md.

**Comment by madflow** [comment]
> To my eye, the file icon with a white background and no 1px border seems to be the best fit for either theme.

Same here!
