### ISSUE TITLE
markdown flavour option(s)

### ISSUE THREAD

**Issue by aplatypus** [madflow/flow-netbeans-markdown#82]
Hi ... I've just installed this with Netbeans 8.0.2; so far working fine.  I particularly like the save as HTML.  I'd like to suggest an enhancement/extension.

_Problem_:  **Need for different markdown and final presentation**

It would be very handy to be able to select the markdown-_flavour_ you need.  Obviously a GitHub project needs the GitHub-_flavour_ and we use MediaWiki quite a bit so support for a MediaWiki-_flavour_ would be extremely useful to many, drupal-_flavour_, foswiki/twiki-_flavour_, etc..  Although GitHub-_flavour_ is nearly same.
1.  I thought there are_different methods_ to satisfy this opportunity:
   generate what it likes (e.g. as JSON, or even PDF).
2.  markdown-**syntax plug-in** support.  User can choose a markdown variant he/she already knows.  No need to learning a _new_ markdown variant.
3.  Save-as option: HTML, MediaWiki, Drupal, Foswiki, GitHub, etc.
4.  Syntax support -- User chooses the markdown _flavour_ for the file.

I definitely favour the **_Save-As plugin**_ option for: "_Save-As_".  On that point, I suggest allowing the user to tick multiple Save-As formats.  There occasions when I'd like my file saved as both: HTML and MediaWiki and perhaps other formats.

On the plug-in idea, I was thinking about '_netbeans_' plug-ins that can be used by _markdown_.  Not "markdown plug-ins" (after all netbeans already has the plug-in plumbing).

**Comment by stengerh** [comment]
I think that support for different Markdown flavours and support for different output formats are two separate and independent features. We use the [pegdown](https://github.com/sirthias/pegdown) library for parsing Markdown and for converting it to HTML. The pegdown library supports some extensions to basic Markdown which you can enable in the NetBeans options window. Switching to another Markdown parser or even implementing our own is out of the scope of this plugin.

An export to PDF can be done by using HTML as an intermediate format. After all Markdown was created to simplify writing HTML pages.

An exporter for some wiki or CMS syntax would have to take the syntax tree produced by pegdown and generate the corresponding code in the target syntax. Of course one could use [pandoc](http://johnmacfarlane.net/pandoc/index.html) to convert between arbitrary syntaxes. We would still need pegdown for syntax highlighting and features like the navigator view. There would be no guarantee that pegdown and pandoc have the same interpretation of the input so the syntax highlighting might not match the preview or output.

Finally I think it would not be good idea to make this plugin extensible. It does not really matter whether we would use the NetBeans plugin system to provide this or some other mechanism. For a project of this size it makes more sense to keep the code in a single place. This keeps the maintenance overhead low for both the developers and the users. If you want to add functionality to the plugin please contribute using a pull request. :)

Back on the topic of Markdown flavours: It might be nice to have presets which activate different sets of Markdown extensions. At some point I also looked into making extensions configurable per project. This would work like per-project formatting options in NetBeans.
