### ISSUE TITLE
Going to preview scrolls down

### ISSUE THREAD

**Issue by jerry1970** [madflow/flow-netbeans-markdown#91]
When going from the Source tab to the Preview tab, the preview is scrolled down to the end of the page. Is it possible to keep the scroll position?

**Comment by madflow** [comment]
See https://github.com/madflow/flow-netbeans-markdown/pull/89. It is already merge into the nb8 branch - but not included in a release yet. If you know how to debug/compile this plugin from source we would appreciate a test.

**Comment by stengerh** [comment]
I prepared a [pre-release](https://github.com/madflow/flow-netbeans-markdown/releases/tag/2.3-preview) containing the recent changes to preserve the scroll position. You are invited to test this pre-release if you do not want to compile the plugin from source code.

I suggest to continue the discussion over at #42.

By the way if the preview jumps to the bottom you are not using the JavaFX based preview. You will need to enable this feature in the plugin's options to benefit from these changes and for the HTML template to affect the preview tab.

**Comment by jerry1970** [comment]
The pre-release 2.3 is recognized as being 2.2 so I had to uninstall the 2.2 first. No problem, but you might want to change it for the proper release.

The problems remain. Maybe I just don't have the right JavaFX version installed even though I can select embedded webkit browser? I am going to download the latest development version of NB (now on 8.0.2 DEV 1 201502020002). And I am going to test 2.3 on my work laptop.

**Comment by jerry1970** [comment]
See #90 , this issue is also solved with 2.3.
