### ISSUE TITLE
Fenced code blocks doesn't work

### ISSUE THREAD

**Issue by hlavki** [madflow/flow-netbeans-markdown#97]
I am using plugin version 2.2 with netbeans 8.0.2 and there is no difference when "Fenced code blocks" extension is ON or OFF. Same result than in #66.

![markdown-01](https://cloud.githubusercontent.com/assets/5858133/9254767/966d34d2-41e5-11e5-9659-04e04694336c.png)
![markdown-02](https://cloud.githubusercontent.com/assets/5858133/9254768/966f2ea4-41e5-11e5-85eb-a676598ff949.png)
![markdown-03](https://cloud.githubusercontent.com/assets/5858133/9254769/96718f14-41e5-11e5-85ec-56391dfb28c0.png)

**Comment by madflow** [comment]
We use a third party library for Markdown parsing and rendering. There is an issue that sounds like what you describe:

https://github.com/sirthias/pegdown/issues/128

So an extra blank line before the code block should make a difference.

**Comment by hlavki** [comment]
thanks @madflow, it works

**Comment by Chris2011** [comment]
For me it doesn't work. I have a block like

``````
#Test

    ``` Java
        tzset
    ```
``````

I enabled each option, but I don't have a code black as you can see it here in github.
