### ISSUE TITLE
Ability to use custom CSS in preview tab is broken in Netbeans 8.0.2

### ISSUE THREAD

**Issue by mfreeman-xtivia** [madflow/flow-netbeans-markdown#98]
This capability (use custom CSS in the preview "tab") seems to be broken and non-functional in Netbeans 8.0.2. I validated this on a fresh copy of Netbeans 8.0.2 with only the Markdown plugin added to the base install.

As an example the CSS below works beautifully when I click on the icon to view in an external browser all of the generated text is RED. When viewed in the editors preview tab it does nothing at all.

![screenshot-options](https://cloud.githubusercontent.com/assets/10734467/9317605/5ecedc4a-4502-11e5-9cd1-f95a1aa757fc.png)

**Comment by madflow** [comment]
I cannot reproduce this. The internal preview uses a JavaFX component for rendering the HTML. Please make sure you have the JavaFX Preview enabled: `Options > Miscellaneous > Markdown > Miscellaneous`

You will need the Oracle JRE/JDK on Linux. The Java Version should be greater than 7u45. The Netbeans "About" Dialog should reveal this.

**Comment by mfreeman-xtivia** [comment]
That was it---was using a non-Oracle JDK. Once I switched to the Oracle JDK everything is golden --thanks for the rapid response.

**Comment by madflow** [comment]
:+1:
